# Generated by Django 4.2.5 on 2023-09-13 14:15

import df_cards.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                ("sequence", models.PositiveIntegerField(default=0)),
                ("title", models.CharField(max_length=255)),
                (
                    "thumbnail",
                    df_cards.fields.ThumbnailImageField(
                        blank=True, null=True, upload_to=""
                    ),
                ),
                (
                    "full_image",
                    df_cards.fields.FullImageField(blank=True, null=True, upload_to=""),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
